# Generated by Django 3.1.7 on 2021-03-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='wines.producer')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='wines.region')),
            ],
            options={
                'ordering': ('-producer', '-region'),
                'unique_together': {('producer', 'region')},
            },
        ),
        migrations.AddField(
            model_name='producer',
            name='presence',
            field=models.ManyToManyField(through='wines.ProducerRegion', to='wines.Region'),
        ),
    ]
