# Generated by Django 3.1.7 on 2021-03-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0007_auto_20210322_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='grape',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='grapealias',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='producerregion',
            options={'ordering': ('producer', 'region')},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='vintage',
            options={'ordering': ('wine', 'year')},
        ),
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='winegrape',
            options={'ordering': ('wine', 'grape')},
        ),
        migrations.AlterField(
            model_name='producer',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_producers', to='wines.region'),
        ),
    ]
