# Generated by Django 3.1.7 on 2021-03-24 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vintage',
            name='year',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
