# Generated by Django 3.1.7 on 2021-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0019_auto_20210327_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='grape',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grapes/%Y/%m/%d/'),
        ),
    ]
