# Generated by Django 3.1.7 on 2021-03-27 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0020_grape_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintage',
            name='alcohol_content',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
