# Generated by Django 3.1.7 on 2021-03-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0024_vintage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='local_wines', to='wines.region'),
        ),
        migrations.AlterUniqueTogether(
            name='wine',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='wine',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'producer'), name='name_type_producer_constraint'),
        ),
    ]
