# Generated by Django 3.1.7 on 2021-03-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0028_grape_tannin'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tannin',
            field=models.IntegerField(choices=[(1, 'Very Weak'), (2, 'Weak'), (3, 'Medium'), (4, 'Strong'), (5, 'Very Strong')], null=True),
        ),
    ]
