# Generated by Django 3.1.7 on 2021-03-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0029_review_tannin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tannin',
        ),
    ]
