# Generated by Django 3.1.7 on 2021-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0030_remove_review_tannin'),
    ]

    operations = [
        migrations.AddField(
            model_name='grape',
            name='acidity',
            field=models.IntegerField(choices=[(1, 'Very Soft'), (2, 'Soft'), (3, 'Medium'), (4, 'Acidic'), (5, 'Very Acidic')], null=True),
        ),
        migrations.AddField(
            model_name='grape',
            name='body',
            field=models.IntegerField(choices=[(1, 'Very Light'), (2, 'Light'), (3, 'Medium'), (4, 'Bold'), (5, 'Very Bold')], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='tannin',
            field=models.IntegerField(choices=[(1, 'Very Smooth'), (2, 'Smooth'), (3, 'Medium'), (4, 'Tannic'), (5, 'Very Tannic')], null=True),
        ),
        migrations.AlterField(
            model_name='grape',
            name='tannin',
            field=models.IntegerField(choices=[(1, 'Very Smooth'), (2, 'Smooth'), (3, 'Medium'), (4, 'Tannic'), (5, 'Very Tannic')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='acidity',
            field=models.IntegerField(choices=[(1, 'Very Soft'), (2, 'Soft'), (3, 'Medium'), (4, 'Acidic'), (5, 'Very Acidic')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.IntegerField(choices=[(1, 'Very Light'), (2, 'Light'), (3, 'Medium'), (4, 'Bold'), (5, 'Very Bold')], null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sweetness',
            field=models.IntegerField(choices=[(1, 'Very Dry'), (2, 'Dry'), (3, 'Medium'), (4, 'Sweet'), (5, 'Very Sweet')], null=True),
        ),
    ]
