# Generated by Django 3.1.7 on 2021-03-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0031_auto_20210329_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grape',
            name='tannin',
        ),
    ]
