# Generated by Django 3.1.7 on 2021-03-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0005_auto_20210322_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grape',
            name='origin',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grapes', to='wines.region'),
            preserve_default=False,
        ),
    ]
