# Generated by Django 3.1.7 on 2021-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0016_auto_20210324_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='countries/%Y/%m/%d/'),
        ),
    ]
